"""
Django settings for gistutorials project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'm3gq=zljfp91j#ecz!dh@7lu=8=dx&j7-2+!n$_i4z))jrb8gq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', 'gistutorials.loc',
                 'gistutorials.com', 'www.gistutorials.com']


# Application definition

INSTALLED_APPS = [
    'ckeditor',
    'leaflet',
    'corsheaders',
    'djoser',
    'rest_framework.authtoken',
    'rest_framework',
    'debug_toolbar',
    'places.apps.PlacesConfig',
    'expenses.apps.ExpensesConfig',
    'quotes.apps.QuotesConfig',
    'articles.apps.ArticlesConfig',
    'members.apps.MembersConfig',
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gistutorials.urls'


###############################################################################
# Hakim: Look for base template at root of project
###############################################################################

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Look for base template at root of project
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # Look for base templatetags at root of project
            'libraries': {
            }
        },
    },
]

WSGI_APPLICATION = 'gistutorials.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'gistutorials',
        'USER': 'hakim',
        'PASSWORD': '78G62h9',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'


###############################################################################
# Hakim: Uploaded images
###############################################################################


# Location of uploaded images

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# URL of uploaded images

MEDIA_URL = '/media/'


###############################################################################
# Hakim: Manage staticfiles
###############################################################################


# Where orginal *.css file is located

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'assets'),
)


# Where the produced static files are generated (e.g. compiled *.css file)

STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Where django look for static files

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)


###############################################################################
# Hakim: Debug bar
###############################################################################


# Whom to show the debug bar for

INTERNAL_IPS = ('127.0.0.1',)


###############################################################################
# Hakim: REST API
###############################################################################


REST_FRAMEWORK = {
    # pagination
    'PAGE_SIZE': 10,
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',

    # authentication required
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
}


###############################################################################
# Hakim: REST CORS
###############################################################################


# Whitelist accounting-web

CORS_ORIGIN_WHITELIST = (
    'localhost:4200',
    'gistutorials.loc',
)
