# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20170219_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
