# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20170207_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quotee',
        ),
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.Author'),
        ),
        migrations.DeleteModel(
            name='Quotee',
        ),
    ]
