# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20170207_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
