# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20170224_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('firstname', 'lastname')},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('firstname', 'lastname')},
        ),
        migrations.AddField(
            model_name='author',
            name='firstname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='author',
            name='lastname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='firstname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='lastname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
