# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20170208_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
