# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_auto_20170226_1907'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set([('firstname', 'lastname')]),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('firstname', 'lastname')]),
        ),
    ]
