# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_auto_20170312_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
