# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-03 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('quotes', '0017_auto_20170803_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
